// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGzR2M2Lk45UWNpywhPR97HHwqnERU7ws',
    appId: '1:1072074737122:web:dc9fd455eee6e2e30f25bb',
    messagingSenderId: '1072074737122',
    projectId: 'ecommerce-frontend-40dae',
    authDomain: 'ecommerce-frontend-40dae.firebaseapp.com',
    storageBucket: 'ecommerce-frontend-40dae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB1sK0n6wzYRx4ASGDoKWxiGdx8YQqwL0',
    appId: '1:1072074737122:android:8a509efa136a1e9d0f25bb',
    messagingSenderId: '1072074737122',
    projectId: 'ecommerce-frontend-40dae',
    storageBucket: 'ecommerce-frontend-40dae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKmoeGmdSe0lk5BmFh0QNAGnoT7-sj2VA',
    appId: '1:1072074737122:ios:f9cd76bd53828a5c0f25bb',
    messagingSenderId: '1072074737122',
    projectId: 'ecommerce-frontend-40dae',
    storageBucket: 'ecommerce-frontend-40dae.appspot.com',
    iosBundleId: 'com.maxonflutter.ecommerce',
  );
}
