// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTSY3ZtEj7L6EdsIHUNHyP40Ms65kHxig',
    appId: '1:838762669833:web:4a7df5f1ebf1ab00e9d5d8',
    messagingSenderId: '838762669833',
    projectId: 'test-4747',
    authDomain: 'test-4747.firebaseapp.com',
    storageBucket: 'test-4747.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHnOy9_UW5ChQvZY6d2aWgSLc8pnliA9U',
    appId: '1:838762669833:android:cd986b8fc404ee92e9d5d8',
    messagingSenderId: '838762669833',
    projectId: 'test-4747',
    storageBucket: 'test-4747.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0-gbYx9Y18H8lfs40fF6FvNRKzFlZ35U',
    appId: '1:838762669833:ios:7cf30c4d8e62722ee9d5d8',
    messagingSenderId: '838762669833',
    projectId: 'test-4747',
    storageBucket: 'test-4747.appspot.com',
    iosBundleId: 'com.example.flutterEcommerceBackend',
  );
}
